config/routes.rb
Rails.application.routes.draw do

  get 'investors/submit_info'
  
  get 'investors/index'

  get 'investors/reg'

  post 'investors/create'

  get 'investors/ban'

  get 'investors/pass'

  resources :post_favors
  get 'users/show_all_posts_by_user_id'
  get 'welcome/get_image_by_id'
  get 'welcome/get_next_15_posts'
  get 'user_active/is_collected'
  get 'user_active/to_follow'
  get 'user_active/cancel_collect_post'
  get 'idea_store/show_post'
  post 'user_active/collect_post'
  get 'user_active/login'
  get 'user_active/reg'
  get 'user_active/logout'
  get 'idea_store/post_a_post'
  get 'idea_store/get_posts'
  get 'idea_store/get_tags'
  get 'idea_store/get_session'
  get 'idea_store/get_one_post'
  get 'idea_store/get_comments'
  get 'idea_store/index'
  get 'idea_store/get_posts_from_topid'

  get 'invitation_admin/get_200_codes'
  get 'invitation_admin/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'
  get 'welcome/show_posts'
  get 'welcome/get_comments'
  get 'welcome/post_one_comment'
  get 'welcome/get_one_post'
  get 'welcome/get_tags'
  get 'get_test/index'
  post 'welcome/get_user_info'

  get 'personal_center/edit'

  post 'personal_center/upload'
  get 'personal_center/upload'
  patch 'personal_center/upload'

  devise_for :admins
  get 'personal_center/index'

  get 'user_mobile/is_name_exist'

  post 'user_mobile/create'
  post 'mobile_new_session/create'
  get 'mobile_new_session/create'

  get 'posts/all'

  post 'posts/all'

  get 'user_mobile/invite_judge'

  resources :posts

  get 'mobile_new_session/destory'

  get 'users/create_remote'

  get 'welcome/index'

  get 'user_sessions/user_exist'

  get 'user_sessions/success_info'

  post 'user_sessions/auth'

  resources :user_sessions

  resources :users

  root 'home#index'

  get 'mobile_app/posts/all'
  get 'mobile_app/posts/new'
  post 'mobile_app/posts/new'
  get 'mobile_app/posts/get'
  post 'mobile_app/posts/get'
  get 'mobile_app/posts/test'
  get 'mobile_app/posts/testName'

  get 'mobile_app/sign/signIn'
  post 'mobile_app/sign/signIn'
  get 'mobile_app/sign/autoSignIn'
  post 'mobile_app/sign/autoSignIn'
  get 'mobile_app/sign/signOut'
  post 'mobile_app/sign/signOut'

  get 'mobile_app/user/setPostFavor'
  post 'mobile_app/user/setPostFavor'
  get 'mobile_app/user/getFavorPosts'
  post 'mobile_app/user/getFavorPosts'
  get 'mobile_app/user/getRootPosts'
  post 'mobile_app/user/getRootPosts'

  get 'mobile_app/tags/all'
  post 'mobile_app/tags/all'

end

app/models/user.rb
class User < ModelBase
	include Mongoid::Document
	attr_accessor :password, :password_confirmation
	include Mongoid::Timestamps
	has_many :user_sessions,  dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :sign_tokens, dependent: :destroy
	has_many :post_favors, dependent: :destroy
	has_many :followers, dependent: :destroy
	has_and_belongs_to_many :tags
	field :name, type: String
	field :email, type: String
	field :mobile, type: String
	field :screct_pass, type: String
	field :invite_code, type: String
	mount_uploader :head_url, AvatarUploader
	validates_confirmation_of :password
	validates :password, confirmation: true
	validates_length_of :name, :within => 3..100
	validates_uniqueness_of :name, :case_sensitive => false, :massage => '用户名已经存在'

	def self.GetCurrentUser(token = nil)
		signTokenId = token ? token : session[:signToken]
		SignToken.find(signTokenId).user
	end

	def isPostFavor(postId)
		return self.post_favors.where(:favor_post_id => postId).exists?
	end

	def setPostFavor(isFavor, postId)
		if isFavor != isPostFavor(postId)
			if isFavor
				PostFavor.NewPostFavor(getId, postId)
			else
				self.post_favors.where(:favor_post_id => postId).first.destroy
			end
		end
		return 0
	end

	def getFavorPosts
		result = []
		self.post_favors.desc(:created_at).each{
			|eachPostFavor|
			result.push(Post.find(eachPostFavor.favor_post_id))
		}
		return result
	end

	def getRootPosts
		return self.posts.desc(:created_at).where(:has_parent => false)
	end

	def auth_pass(pass)
		if self.screct_pass == self.md5(pass)
			self
		else
			nil
		end
	end

	def md5(pass)
		Digest::MD5.hexdigest(pass)
	end

end

app/controllers/mobile_app/user_controller.rb
class MobileApp::UserController < ApplicationController
	use Rack::Cors do
		allow do
			origins '*', 'null'
			resource '*', :headers => :any, :methods => [:get, :post]
		end
	end
	skip_before_filter :verify_authenticity_token, only: [:setPostFavor, :getFavorPosts, :getRootPosts]

	# 设置用户帖子收藏关系
	# 参数：isFavor收藏关系true/false post[id]帖子id
	# 浏览器端参数：token用户验证
	# 成功：0
	# 失败：-1
	def setPostFavor
		currentUser = User.GetCurrentUser(params[:token])
		currentUser.setPostFavor(params[:isFavor] == "true", params[:post][:id])
		render json: 0
	end

	# 获取用户收藏的帖子
	# 浏览器端参数：token用户验证
	# 返回：{posts:[{post:{id:*, title:*, content:*}, user:{id:*, name:*}}, ...}
	def getFavorPosts
		result = []
		currentUser = User.GetCurrentUser(params[:token])
		currentUser.getFavorPosts.each{
			|eachFavorPost|
			result.push(eachFavorPost.getPostAndUser)
		}
		render json: {"posts": result}
	end

	# 获取用户发布的帖子（根帖子，不包含子帖子）
	# 浏览器端参数：token用户验证
	# 返回：{posts:[{post:{id:*, title:*, content:*}}, ...}
	def getRootPosts
		result = []
		currentUser = User.GetCurrentUser(params[:token])
		currentUser.getRootPosts.each{
			|eachPost|
			result.push({"post": eachPost.getPost})
		}
		render json: {"posts": result}
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'foundation_view.html.erb', only: [:show, :show_all_posts_by_user_id]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if session[:progress]
      @user_session = UserSession.find(session[:progress].fetch("_id").fetch("$oid"))
    end
  end

  def show_all_posts_by_user_id
    if params[:user_id]
      @user = User.find(params[:user_id])
    end
    @title = '我发表的帖子'
    @page = 1
    if params[:page]
      @page = params[:page].to_i
    end
    if params[:first]
      @page = 1
    end
    if params[:last]
      @page = @page.to_i + 1
      
    end
    if session[:progress]
      @user_session = UserSession.find(session[:progress].fetch("_id").fetch("$oid"))
    end
    if @user_session.user.eql?(@user)
       @posts = Post.where(:title.gt => '', :user_id => @user_session.user.id).desc(:created_at).page(@page).per(15).pluck(:id, :title, :image_item_ids, :created_at, :tag_ids, :is_published)
    else
      @posts = Post.where(:title.gt => '', :user_id => @user.id).desc(:created_at).page(@page).per(15).pluck(:id, :title, :image_item_ids, :created_at, :tag_ids, :is_published)
    end
   
    #@posts = Post.order('created_at').page(1)
    @post = Post.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.screct_pass = @user.md5(user_params[:password].to_s)
    @invite_code = Invitation.where(code: @user.invite_code).first
     if @invite_code.nil?
      if params[:page] == 'foundation'
          redirect_to user_active_reg_path, notice: '邀请码不正确'.html_safe()
          return nil
      else
        redirect_to new_user_session_path, notice: '邀请码不正确！'
        return nil
      end
       
     else
       @invite_code.destroy
     end
    respond_to do |format|
      if @user.save
        if params[:page]=='foundation'
          format.html { redirect_to user_active_login_path, notice:'注册成功，请登录' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { redirect_to new_user_session_path, notice:'注册成功，请登录' }
          format.json { render :show, status: :created, location: @user }
        end
        
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :screct_pass, :invite_code, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= javascript_include_tag "user_active.js"%>
<%= form_for @user, :html => {:class => 're_form', :id => 're_form' } do |f| %>
<% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li> 
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
    
    <%= form_for @user, url: user_sessions_auth_path, html:{class: 'am-form', id: 'doc-vld-msg'} do |f| %>
   
    <legend>新用户注册</legend>
      <div class="am-form-group am-form-icon">
    <i class="am-icon-user"></i>
   
    <%= f.text_field :name, placeholder: "用户名", class: "am-form-field field-usename" %>
  </div>
  <div class="Balert"><i class="am-icon-bolt"></i>&nbsp;英文字母,数字,字符长度5-25位</div>
  

  <div class="am-form-group am-form-icon">
    <i class="am-icon-lock"></i>
    <%= f.password_field :password, placeholder: "密码", class: "am-form-field field-password" %>
  </div>
  <div class="Balert1"><i class="am-icon-bolt"></i>&nbsp;6-12位，输入字符无限制</div>
   <div class="am-form-group am-form-icon">
    <i class="am-icon-lock"></i>
    
    <%= f.password_field :password_confirmation, placeholder: "密码确认", class: "am-form-field field-password2" %>
  </div>
  <div class="Balert2"><i class="am-icon-bolt"></i>&nbsp;输入密码与设置密码内容一致</div>
   <div class="am-form-group am-form-icon">
    <i class="am-icon-joomla"></i>
    <%= f.text_field :invite_code, placeholder: "邀请码", class: "am-form-field field-invitecode" %>
  </div>
  <div class="Balert3"><i class="am-icon-bolt"></i>&nbsp;必须输入且正确的邀请码才可以成功注册</div>


        <div class="am-checkbox">
          <label>
            <input type="checkbox"> 阅读并且同意 <a href="">《xx服务协议xx》</a>
          </label>
        </div>
    
        <button type="submit" class="am-btn am-btn-secondary  am-btn-block">注&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;册</button>
    </form>
 <% end %>
<!--      <%= f.text_field :name, id:"doc-vld-name-2", minlength:"3", placeholder:"只能英文字母、数字、中文中的一种或者混搭", required: 1 %>-->

<!--      <%= f.password_field :password, id: "doc-vld-pwd-1", placeholder: "6-12位，输入字符无限制", pattern: '^\w{6,12}$'.to_s, required: 1,  'data-foolish-msg': "请输入正确位数的密码！" %>-->
     
<!--      <%= f.password_field :password_confirmation, id: "doc-vld-pwd-2", placeholder: "必须与设置密码内的内容一致", 'data-equal-to': "#doc-vld-pwd-1", required: 1, 'data-foolish-msg': "两次密码不一致" %>-->
     
<!--      <%= f.password_field :invite_code, id: "doc-vld-pwd-1-0", placeholder: "必须输入正确的邀请码才能登录", pattern: '^\d{4}$'.to_s, required: 1, 'data-foolish-msg': "请输入正确的邀请码！" %>-->
    <% end %>
  <script>
    
    $(function() {
      $("#doc-vld-name-2").blur(function(event) {
           $.get("<%= user_sessions_user_exist_path %>?user[user_attr]="+$(this).val(), function(data){
              if (data=='1') {
                alert('用户名已存在');
              }
              if (data=='0') {
                alert('用户名可用')
              }
          });
      });
     
  $('#doc-vld-msg').validator({
    onValid: function(validity) {
      $(validity.field).closest('.am-form-group').find('.am-alert').hide();
    },
    onInValid: function(validity) {
      var $field = $(validity.field);
      var $group = $field.closest('.am-form-group');
      var $alert = $group.find('.am-alert');
      // 使用自定义的提示信息 或 插件内置的提示信息
      var msg = $field.data('validationMessage') || this.getValidationMessage(validity);

      if (!$alert.length) {
        $alert = $('<div class="am-alert am-alert-danger"></div>').hide().
          appendTo($group);
      }

      $alert.html(msg).show();

    }
  });
});
$(document).ready(function(){
  $(".field-usename").focus(function(){
       $(".Balert").slideDown("fast");
  });
    $(".field-usename").blur(function(){
         var reuse=/^[a-zA-Z0-9_]{5,25}$/g;
        if (!reuse.test($(".field-usename").val())){
              if($(".field-usename").val()==="")
        {
         $(".Balert").html('<i class="am-icon-frown-o"></i>&nbsp;用户名不能为空')
        }
            else{
           $(".Balert").html('<i class="am-icon-frown-o"></i>&nbsp;该用户名不可用')
        }
        }
        else{
           params={'user[user_attr]':$(".field-usename").val()};
            $obj=$('.Balert');
            url= '<%= user_sessions_user_exist_path %>';
            flag= 'user_exist_yes';
            ByGet(params, $obj, url, flag);
            $(".Balert").html('<i class="am-icon-smile-o"></i>&nbsp;用户名可用')
        }; 
    });
});
//密码验证
$(document).ready(function(){
  $(".field-password").focus(function(){
       $(".Balert1").slideDown("fast");
  });
    $(".field-password").blur(function(){
        var reuse=/^[a-zA-Z0-9_]{6,12}$/g;
   if (!reuse.test($(".field-password").val())){
              if($(".field-password").val()==="")
        {
         $(".Balert1").html('<i class="am-icon-frown-o"></i>&nbsp;密码不能为空')
        }
            else{
           $(".Balert1").html('<i class="am-icon-frown-o"></i>&nbsp;密码长度不对或者含有非法字符')
        }
        }
        else{
              $(".Balert1").html('<i class="am-icon-smile-o"></i>&nbsp;OK')
        }; 
    });
});
//密码二次验证
$(document).ready(function(){
  $(".field-password2").focus(function(){
       $(".Balert2").slideDown("fast");
  });
  $(".field-password2").blur(function(){
   if (!($(".field-password2").val()==$(".field-password").val())){
              if($(".field-password2").val()==="")
        {
         $(".Balert2").html('<i class="am-icon-smile-o"></i>&nbsp;此项不能为空')
        }
            else{
           $(".Balert2").html('<i class="am-icon-frown-o"></i>&nbsp;两次输入密码不一致')
        }
        }
        else{
              $(".Balert2").html('<i class="am-icon-smile-o"></i>&nbsp;OK')
        }; 
    });
});
//验证码验证
$(document).ready(function(){
  $(".field-invitecode").focus(function(){
       $(".Balert3").slideDown("fast");
  });
$(".field-invitecode").blur(function(){
     var reuse=/^[a-zA-Z0-9_]{4}$/g;
        if (reuse.test($(".field-invitecode").val())){
            $(".Balert3").html('<i class="am-icon-smile-o"></i>&nbsp;OK')
        }
        else{
             $(".Balert3").html('<i class="am-icon-frown-o"></i>&nbsp;邀请码不正确')
        };
    });
});
</script>

<!--<![endif]-->

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Screct pass</th>
      <th>Invite code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.screct_pass %></td>
        <td><%= user.invite_code %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="rg_content">
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div>
  
  <div class="row" id="userinfo">
    <div class="medium-3 large-3 small-4 columns">
      <%= image_tag(@user.head_url.thumb) %>
    </div>
    <div class="medium-4 large-4 small-4 columns">
      <div class="row">
        <div class="medium-6 columns">用户名：</div>
        <div class="medium-6 columns"><%=@user.name %></div>
      </div>
      <div><hr></div>
      <div class="row">
        <div class="medium-6 columns">关注:</div>
        <div class="medium-6 columns">被关注:</div>
      </div>
      <div class='row'>
        <div class="medium-6 columns"><%= Follower.where(follower_id: @user.id).count %></div>
        <div class="medium-6 columns"><%= @user.followers.count %></div>
      </div>
      <div><hr></div>
    </div>
    <div class="medium-4 large-4 small-4 columns"></div>
  </div>
  <div>
    <hr>
  </div>
  <div class="row">
    <div class="medium-1 large-1 small-1 columns"></div>
    <div class="medium-9 large-9 small-9 columns"><h4>我发表过的帖子：</h4><hr></div>
    <div class="medium-9 large-2 small-2 columns"><%= link_to '更多',users_show_all_posts_by_user_id_path(user_id: @user.id), class: 'button small' %></div>
  </div>
  <% @user.posts.limit(5).each do |post| %>
   <div class="row">
    <div class="medium-1 large-1 small-1 columns">&nbsp;</div>
    <div class="medium-8 large-8 small-8 columns"><%= post.title%></div>
    <div class="medium-2 large-2 small-2 columns">
      <span>
      <% if @user_session.user.eql?(@user) %>
      <%= link_to '删除', post_path(post,:from_user => 1,:user_id => post.user.id), method: :delete, data: { confirm: '你确定删除?' } %>

    </span><span>编辑</span>
    <% end %>
    <span>查看</span>
    </div>
    <div class="medium-1 large-1 small-1 columns"></div>
  </div>
  <% end %>
  <div class="row">
    <hr>
  </div>
  <div class="row">
    <div class="medium-1 large-1 small-1 columns"></div>
    <div class="medium-9 large-9 small-9 columns"><h4>我收藏的帖子：</h4><hr></div>
    <div class="medium-2 large-2 small-2 columns"><a href="#" class="button small"><small>更多</small></a></div>
  </div>
  <% @user.post_favors.each do |favor| %>
  <div class="row">
    <div class="medium-1 large-1 small-1 columns">&nbsp;</div>
    <div class="medium-8 large-8 small-8 columns"><%= Post.find(favor.favor_post_id).title %></div>
    <div class="medium-2 large-2 small-2 columns"><span>取消收藏
    </span><span>查看</span><span>编辑</span></div>
    <div class="medium-1 large-1 small-1 columns"></div>
  </div>
  <% end %>
</div>
<div>
  <div>
  </div>
</div>
<br><br><br>

app/views/users/show_all_posts_by_user_id.html.erb
<style>
	.display{
		max-width: 100% !important;
		width: 100% !important;
		text-align: center !important;
		padding-left: 1rem !important;
		padding-right: 1rem !important;
	}
	
	
</style>

<div class="row">
	<ul class="breadcrumbs">
  <li><a href="#">首页</a></li>
  <li><a href="#">脑库</a></li>
  <li class="unavailable"><a href="#">Gene Splicing</a></li>
  <li class="current"><a href="#">Cloning</a></li>
</ul>
</div>
<section id="scrollerBox" class="scroll-container  display">
<br>
<div class="row display">
<h4><%= @user.name %>的所有帖子</h4>
	<div class="row display"  data-equalizer='foo' data-equalizer-mq >
	<% @posts.each_with_index do |post,index| %>
	<div post-id='<%= post[0]%>' class='row'>
	<div class='medium-6 large-6 small-6 columns'><%= post[1]%></div>
	<div class='medium-4 large-4 small-4 columns'><span><%= link_to '删除', post_path(post[0],:from_user_all => 1, :user_id => @user.id), method: :delete, data: { confirm: '你确定删除?' } %></span></div>
	<div class='medium-2 large-2 small-2 columns'><span class='small'><small>创建于:</small></span><%= post[3]%></div>
	</div>
		
	<% end %>
</div>
<script type="text/javascript">
	$(".panel").each(function(index, el) {
		if(index%3 == 0){
			$(this).addClass('callout')
		}	
	});
</script>
</section>
<div class="row pageDisplay">
<br>
	<div class="small-2 medium-3 large-3 columns columnsDisplay"></div>
	<div class="small-6 medium-6 large-6 columns columnsDisplay">
		<ul class="pagination">
		  <li class="arrow unavailable"><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i %>&first=1">&laquo;</a></li>
		  <% if @page.to_i < 2 and @page.to_i > 1 %>
		  <li><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id) %>&page=<%=@page-1 %>"><%= @page -1 %></a></li>
		  <% end %>
		  <% if @page.to_i < 4 and @page.to_i > 1 %>
		  <li><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page-2 %>"><%= @page - 2 %></a></li>
		  <li><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>?page=<%=@page-1 %>"><%= @page -1 %></a></li>
		  <% end %>
		  <li class="current"><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i %>"><%= @page.to_i %></a></li>
		  <li><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i+1%>"><%= @page.to_i+1 %></a></li>
		  <li><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i+2 %>"><%= @page.to_i+2 %></a></li>
		  <li class="unavailable"><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i+5 %>">&hellip;</a></li>
		  <li><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i+9 %>"><%= @page.to_i+9 %></a></li>
		  <li class="arrow"><a href="<%= users_show_all_posts_by_user_id_path(user_id: @user.id)  %>&page=<%=@page.to_i %>&last=1">&raquo;</a></li>
		</ul>
	</div>
	<div class="small-4 medium-3 large-3 columns columnsDisplay">
  
	</div>
	<br>
	
</div>
<div style="text-align:center">
		© 2015 <a href="<%= root_url %>" target="_blank">Laiber, Inc
	</div>