config/routes.rb
Rails.application.routes.draw do

  get 'investors/submit_info'
  
  get 'investors/index'

  get 'investors/reg'

  post 'investors/create'

  get 'investors/ban'

  get 'investors/pass'

  resources :post_favors
  get 'users/show_all_posts_by_user_id'
  get 'welcome/get_image_by_id'
  get 'welcome/get_next_15_posts'
  get 'user_active/is_collected'
  get 'user_active/to_follow'
  get 'user_active/cancel_collect_post'
  get 'idea_store/show_post'
  post 'user_active/collect_post'
  get 'user_active/login'
  get 'user_active/reg'
  get 'user_active/logout'
  get 'idea_store/post_a_post'
  get 'idea_store/get_posts'
  get 'idea_store/get_tags'
  get 'idea_store/get_session'
  get 'idea_store/get_one_post'
  get 'idea_store/get_comments'
  get 'idea_store/index'
  get 'idea_store/get_posts_from_topid'

  get 'invitation_admin/get_200_codes'
  get 'invitation_admin/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'
  get 'welcome/show_posts'
  get 'welcome/get_comments'
  get 'welcome/post_one_comment'
  get 'welcome/get_one_post'
  get 'welcome/get_tags'
  get 'get_test/index'
  post 'welcome/get_user_info'

  get 'personal_center/edit'

  post 'personal_center/upload'
  get 'personal_center/upload'
  patch 'personal_center/upload'

  devise_for :admins
  get 'personal_center/index'

  get 'user_mobile/is_name_exist'

  post 'user_mobile/create'
  post 'mobile_new_session/create'
  get 'mobile_new_session/create'

  get 'posts/all'

  post 'posts/all'

  get 'user_mobile/invite_judge'

  resources :posts

  get 'mobile_new_session/destory'

  get 'users/create_remote'

  get 'welcome/index'

  get 'user_sessions/user_exist'

  get 'user_sessions/success_info'

  post 'user_sessions/auth'

  resources :user_sessions

  resources :users

  root 'home#index'

  get 'mobile_app/posts/all'
  get 'mobile_app/posts/new'
  post 'mobile_app/posts/new'
  get 'mobile_app/posts/get'
  post 'mobile_app/posts/get'
  get 'mobile_app/posts/test'
  get 'mobile_app/posts/testName'

  get 'mobile_app/sign/signIn'
  post 'mobile_app/sign/signIn'
  get 'mobile_app/sign/autoSignIn'
  post 'mobile_app/sign/autoSignIn'
  get 'mobile_app/sign/signOut'
  post 'mobile_app/sign/signOut'

  get 'mobile_app/user/setPostFavor'
  post 'mobile_app/user/setPostFavor'
  get 'mobile_app/user/getFavorPosts'
  post 'mobile_app/user/getFavorPosts'
  get 'mobile_app/user/getRootPosts'
  post 'mobile_app/user/getRootPosts'

  get 'mobile_app/tags/all'
  post 'mobile_app/tags/all'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
  	
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
  <style>
    .get {
/*      background-image: url(images/index.jpg);*/
      color: #fff;
      text-align: center;
     /* padding: 100px 0;*/
        height: auto;
    }

    .get-title {
      font-size: 200%;
      border: 2px solid #fff;
      padding: 20px;
      display: inline-block;
    }

    .get-btn {
      background: #fff;
    }

    .detail {
      background: #fff;
    }

    .detail-h2 {
      text-align: center;
      font-size: 150%;
      margin: 40px 0;
    }

    .detail-h3 {
      color: #1f8dd6;
    }

    .detail-p {
      color: #7f8c8d;
    }

    .detail-mb {
      margin-bottom: 30px;
    }

    .hope {
      background: #0bb59b;
      padding: 50px 0;
    }

    .hope-img {
      text-align: center;
    }

    .hope-hr {
      border-color: #149C88;
    }

    .hope-title {
      font-size: 140%;
    }

    .about {
      background: #fff;
      padding: 40px 0;
      color: #7f8c8d;
    }

    .about-color {
      color: #34495e;
    }

    .about-title {
      font-size: 180%;
      padding: 30px 0 50px 0;
      text-align: center;
    }

    .footer p {
      color: #7f8c8d;
      margin: 0;
      padding: 15px 0;
      text-align: center;
      background: #2d3e50;
    }
  </style>
<body>
<header class="am-topbar am-topbar-fixed-top">
  <div class="am-container">
    <h1 class="am-topbar-brand">
      <a href="<%= root_url %>"><%=image_tag 'laiber_logo.png', style: "height: 40px;" %> </a>
    </h1>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-secondary am-show-sm-only"
            data-am-collapse="{target: '#collapse-head'}"><span class="am-sr-only">导航切换</span> <span
        class="am-icon-bars"></span></button>
   
    <div class="am-collapse am-topbar-collapse" id="collapse-head">
      <ul class="am-nav am-nav-pills am-topbar-nav">
        <li class="am-active"><a href="<%= root_url %>">首页</a></li>
        <li><a href="javascript: window.location.assign('<%= idea_store_index_path %>');" data-ajax="false">脑库</a></li>

      </ul>
      <%
        if session[:progress]
          user_session = UserSession.find(session[:progress].fetch("_id").fetch("$oid"))
        end
        if user_session
       %>
       <div class="am-topbar-right">
       <%= link_to '<span class="am-icon-user"></span> 登出'.html_safe(), user_session_path(user_session),
               method: :delete,
               data: { confirm: '您确定不?' }, class: "am-btn am-btn-secondary am-topbar-btn am-btn-sm", style:"color:white;" %>
      </div>
        <div class="am-topbar-right">
        <%= link_to user_session.name.to_s, user_path(user_session.user), class: "am-btn am-btn-secondary am-topbar-btn am-btn-sm", style:"color:white;" %>
      </div>
      <% else %>
      <div class="am-topbar-right">
        <a href="<%= new_user_session_path %>" class="am-btn am-btn-secondary am-topbar-btn am-btn-sm" style="color:white;"><span class="am-icon-user"></span> 登录/注册</a>
      </div>
      <% end %>
    </div>
  </div>
</header>

<div class="get" >
<div class="am-slider am-slider-default" data-am-flexslider="{controlNav: false,directionNav:false  }">
  <ul class="am-slides">
     <li><%= image_tag "index11.jpg" %></li>
      <li><%= image_tag "index3.jpg" %></li>
      <li><%= image_tag "index4.jpg" %></li>
     <li><%= image_tag "index10.jpg" %></li>
    
    <!-- <li><%= image_tag "index1.jpg" %></li> -->
   
    
  </ul>
</div>
</div>
<!--

<div class="detail">
  <div class="am-g am-container">
    <div class="am-u-lg-12">
      <h2 class="detail-h2"> 我们的梦想，我们自己来吧!</h2>

      <div class="am-g">
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">

          <h3 class="detail-h3">
            <i class="am-icon-mobile am-icon-sm"></i>
            玩法介绍
          </h3>

          <p class="detail-p">
        噼里噼里噼里噼里噼里噼里一大堆
          </p>
        </div>
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">
          <h3 class="detail-h3">
            <i class="am-icon-cogs am-icon-sm"></i>
             热门创意
          </h3>

          <p class="detail-p">
            噼里噼里噼里噼里噼里噼里一大堆
          </p>
        </div>
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">
          <h3 class="detail-h3">
            <i class="am-icon-check-square-o am-icon-sm"></i>
            项目孵化
          </h3>

          <p class="detail-p">
             噼里噼里噼里噼里噼里噼里一大堆
          </p>
        </div>
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">
          <h3 class="detail-h3">
            <i class="am-icon-send-o am-icon-sm"></i>
          线下支持
          </h3>

          <p class="detail-p">
           噼里噼里噼里噼里噼里噼里一大堆
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
-->

<!--
<div class="hope">
  <div class="am-g am-container">
    <div class="am-u-lg-4 am-u-md-6 am-u-sm-12 hope-img">
      
      <%= image_tag 'landing.png', 'ata-am-scrollspy': "{animation:'slide-left', repeat: false}"  %>
      <hr class="am-article-divider am-show-sm-only hope-hr">
    </div>
    <div class="am-u-lg-8 am-u-md-6 am-u-sm-12">
      <h2 class="hope-title">我们一起玩泥巴</h2>

      <p> 
        在知识爆炸的年代，继续噼里噼里噼里噼里噼里噼里一大堆噼里噼里噼里噼里噼里噼里一大堆
      </p>
    </div>
  </div>
</div>  
-->



<footer class="footer">
  <p style="background-color: white;">© 2015 <a href="http://www.laiber.ml" target="_blank">Laiber, Inc.</a> Licensed under <a
      href="http://opensource.org/licenses/MIT" target="_blank"></a>. by the Ulaiber.</p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/polyfill/rem.min.js"></script>
<script src="assets/js/polyfill/respond.min.js"></script>
<script src="assets/js/amazeui.legacy.js"></script>
<![endif]-->
<!--<![endif]-->
</body>