config/routes.rb
Rails.application.routes.draw do

  get 'investors/submit_info'
  
  get 'investors/index'

  get 'investors/reg'

  post 'investors/create'

  get 'investors/ban'

  get 'investors/pass'

  resources :post_favors
  get 'users/show_all_posts_by_user_id'
  get 'welcome/get_image_by_id'
  get 'welcome/get_next_15_posts'
  get 'user_active/is_collected'
  get 'user_active/to_follow'
  get 'user_active/cancel_collect_post'
  get 'idea_store/show_post'
  post 'user_active/collect_post'
  get 'user_active/login'
  get 'user_active/reg'
  get 'user_active/logout'
  get 'idea_store/post_a_post'
  get 'idea_store/get_posts'
  get 'idea_store/get_tags'
  get 'idea_store/get_session'
  get 'idea_store/get_one_post'
  get 'idea_store/get_comments'
  get 'idea_store/index'
  get 'idea_store/get_posts_from_topid'

  get 'invitation_admin/get_200_codes'
  get 'invitation_admin/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'
  get 'welcome/show_posts'
  get 'welcome/get_comments'
  get 'welcome/post_one_comment'
  get 'welcome/get_one_post'
  get 'welcome/get_tags'
  get 'get_test/index'
  post 'welcome/get_user_info'

  get 'personal_center/edit'

  post 'personal_center/upload'
  get 'personal_center/upload'
  patch 'personal_center/upload'

  devise_for :admins
  get 'personal_center/index'

  get 'user_mobile/is_name_exist'

  post 'user_mobile/create'
  post 'mobile_new_session/create'
  get 'mobile_new_session/create'

  get 'posts/all'

  post 'posts/all'

  get 'user_mobile/invite_judge'

  resources :posts

  get 'mobile_new_session/destory'

  get 'users/create_remote'

  get 'welcome/index'

  get 'user_sessions/user_exist'

  get 'user_sessions/success_info'

  post 'user_sessions/auth'

  resources :user_sessions

  resources :users

  root 'home#index'

  get 'mobile_app/posts/all'
  get 'mobile_app/posts/new'
  post 'mobile_app/posts/new'
  get 'mobile_app/posts/get'
  post 'mobile_app/posts/get'
  get 'mobile_app/posts/test'
  get 'mobile_app/posts/testName'

  get 'mobile_app/sign/signIn'
  post 'mobile_app/sign/signIn'
  get 'mobile_app/sign/autoSignIn'
  post 'mobile_app/sign/autoSignIn'
  get 'mobile_app/sign/signOut'
  post 'mobile_app/sign/signOut'

  get 'mobile_app/user/setPostFavor'
  post 'mobile_app/user/setPostFavor'
  get 'mobile_app/user/getFavorPosts'
  post 'mobile_app/user/getFavorPosts'
  get 'mobile_app/user/getRootPosts'
  post 'mobile_app/user/getRootPosts'

  get 'mobile_app/tags/all'
  post 'mobile_app/tags/all'

end

app/models/post.rb
class Post < ModelBase
	include Mongoid::Document
	include Mongoid::Timestamps
	field :title, type: String
	field :content, type: String
	field :num_children, type: Integer, default: 0
	field :has_parent, type: Boolean, default: false
	field :is_publish, type: Integer, default: 1
	has_many :post_children
	has_one :post_parent
	belongs_to :user
	belongs_to :recommand_list
	has_and_belongs_to_many :tags
	has_and_belongs_to_many :image_items

	def self.GetPosts(limit = nil)
		return Post.Get(limit)
	end

	def self.GetRootPosts(limit = nil)
		return Post.Get.where(:has_parent => false).limit(limit)
	end

	def self.GetRootPublishedPosts(limit = nil)
		return Post.Get.where(:has_parent => false, :is_publish => 1).limit(limit)
	end

	def self.GetRootPostsForTop(topPostId, limit = nil)
		topPostCreatedAt = Post.find(topPostId).created_at
		return Post.Get.where(:has_parent => false).where(:created_at.gt => topPostCreatedAt).limit(limit)
	end

	def self.GetRootPostsForBottom(bottomPostId, limit = nil)
		bottomPostCreatedAt = Post.find(bottomPostId).created_at
		return Post.Get.where(:has_parent => false).where(:created_at.lt => bottomPostCreatedAt).limit(limit)
	end
	def self.GetRootPublishedPostsForBottom(bottomPostId, limit = nil)
		bottomPostCreatedAt = Post.find(bottomPostId).created_at
		return Post.Get.where(:has_parent => false).where(:created_at.lt => bottomPostCreatedAt).limit(limit)
	end

	def self.GetPostsFromParentPost(parentPostId, limit = nil)
		result = []
		parentPost = Post.find(parentPostId)
		parentPost.post_children.Get(limit).each{
			|x|
			result.push(Post.find(x.child_post_id))
		}
		return result
	end

	def self.GetPostsForTopFromParentPost(topPostId, parentPostId, limit = nil)
		result = []
		parentPost = Post.find(parentPostId)
		topPostCreatedAt = PostChild.where(:child_post_id => topPostId).first.created_at
		parentPost.post_children.Get.where(:created_at.gt => topPostCreatedAt).limit(limit).each{
			|x|
			result.push(Post.find(x.child_post_id))
		}
		return result
	end

	def self.GetPostsForBottomFromParentPost(bottomPostId, parentPostId, limit = nil)
		result = []
		parentPost = Post.find(parentPostId)
		bottomPostCreatedAt = PostChild.where(:child_post_id => bottomPostId).first.created_at
		parentPost.post_children.Get.where(:created_at.lt => bottomPostCreatedAt).limit(limit).each{
			|x|
			result.push(Post.find(x.child_post_id))
		}
		return result
	end

	def self.NewPost(postTitle, postContent, userId, parentPostId = nil)
		post = Post.new
		post.title = postTitle
		post.content = postContent
		post.user = User.find(userId)
		post.has_parent = parentPostId ? true : false
		post.save

		if parentPostId
			parentPost = Post.find(parentPostId)
			parentPost.num_children += 1
			parentPost.save
			postId = post.getId

			PostParent.NewPostParent(postId, parentPostId)
			PostChild.NewPostChild(parentPostId, postId)
		end

		return post
	end

	def self.DeletePost(postId)
		post = Post.find(postId)
		PostFavor.where(:favor_post_id => postId).each{
			|eachPostFavor|
			eachPostFavor.destroy
		}
		if post.has_parent
			postParent = post.post_parent
			parentPost = Post.find(postParent.parent_post_id)
			parentPost.num_children -= 1
			parentPost.save

			postChild = parentPost.post_children.where(:child_post_id => post.getId)
			postChild.destroy

			postParent.destroy
		end
		if post.num_children > 0
			post.post_children.each{
				|eachPostChild|
				Post.DeletePost(eachPostChild.child_post_id)
				eachPostChild.destroy
			}
		end
		post.destroy
		return 0
	end

	def getPost
		return {"id": getId, "title": self.title, "content": self.content, "created_at": self.created_at}
	end

	def getUser
		return {"id": getId, "name": self.user.name}
	end
	
	def getTags
		result = []
		self.tags.each_with_index{
			|x|
			result.push({"id": x.getId, "name": x.name})
		}
		return result
	end

	def getPostAndUser
		return {"post": getPost, "user": getUser}
	end

	def getPostAndUserAndIsFavor
		return {"post": getPost, "user": getUser, "isFavor": self.user.isPostFavor(getId)}
	end

	def getPostAndUserAndTags
		return {"post": getPost, "user": getUser, "tags": getTags}
	end

	
end

app/controllers/idea_store_controller.rb
class IdeaStoreController < ApplicationController
  layout 'foundation_view'
  def index
  	@title = 'Laiber——改变世界的愿景'
    @page = 1
    if params[:page]
      @page = params[:page].to_i
    end
    if params[:first]
      @page = 1
    end
    if params[:last]
      @page = @page.to_i + 1
      
    end
    @posts = Post.where(:title.gt => '',:is_publish => 1 ).desc(:created_at).page(@page).per(15).pluck(:id, :title, :image_item_ids, :created_at, :tag_ids)
    #@posts = Post.order('created_at').page(1)
    @post = Post.new
  end

  def post_a_post
    @post = Post.new 
    if params[:draft_id]
      @post_draft = Post.find(params[:draft_id]);
    end
    @user_session = nil
    if session[:progress]
      @user_session = UserSession.find(session[:progress].fetch("_id").fetch("$oid"))
    else
     redirect_to user_active_login_path, notice: '请先登录！'
    end
    
    
  end

  def get_posts
  	@title = 'Laiber——改变世界的愿景'
    @posts = Post.where(:title.gt => '' ).desc(:created_at).limit(15).pluck(:id, :title, :image_item_ids, :created_at, :tag_ids)
    @post = Post.new
    render json: @posts
  end

  def get_tags
  	render json: Tag.all
  end

  def get_session
  	@user_session = nil
  	if session[:progress]
      @user_session = UserSession.find(session[:progress].fetch("_id").fetch("$oid"))
    end
    render json: @user_session
  end

  def get_one_post
  	@post = Post.find(params[:post_id])
  	render json: @post
  end

  def get_comments
  	if params[:limit]
  		render json: Post.GetPostsFromParentPost(params[:parent_id], params[:limit])
  	else
  		render json: Post.GetPostsFromParentPost(params[:parent_id], nil)
  	end
  end

  def show_post
    @user_session = nil
    if session[:progress]
      @user_session = UserSession.find(session[:progress].fetch("_id").fetch("$oid"))
    end
    if params[:post_id]
      @post = Post.find(params[:post_id])
    else
      redirect_to idea_store_index_path
    end
  end

  def get_post_from_topid
  	
  end

end

app/helpers/idea_store_helper.rb
module IdeaStoreHelper
end

app/views/idea_store/index.html.erb
<style>
	.display{
		max-width: 100% !important;
		width: 100% !important;
		text-align: center !important;
		padding-left: 1rem !important;
		padding-right: 1rem !important;
	}
	
	
</style>

<div class="row">
	<ul class="breadcrumbs">
  <li><a href="#">首页</a></li>
  <li><a href="#">脑库</a></li>
  <li class="unavailable"><a href="#">Gene Splicing</a></li>
  <li class="current"><a href="#">Cloning</a></li>
</ul>
</div>
<section id="scrollerBox" class="scroll-container  display">
<br>
<div class="row display">
	<div class="row"  data-equalizer='foo' data-equalizer-mq >
	<% @posts.each_with_index do |post,index| %>
		<% if (index/4) >= 1 and (index%4) == 0 %>
	  	</div><div class="row" data-equalizer='foo' data-equalizer-mq="foo" ><div class="small-12 medium-3 large-3 columns" >
	  	<div data-equalizer-watch="foo" class="panel" >
	  	<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
	  	<h4><%= post[1] %></h4></a>
	  	

	  	<% if post[2] %>
	  		<% if ImageItem.find(post[2][0]).url_from_content.include?('ttp:') %>
	  		<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
	  			<img src="h<%= ImageItem.find(post[2][0]).url_from_content %>"  alt="">
	  			</a>
	  		<% else %>
	  		<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
				<img src="../<%= ImageItem.find(post[2][0]).url_from_content %>"  alt="">
				</a>
	  		<% end %>
	  	<% else %>
	  	<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
			<%= image_tag 'default.jpg', alt: '图片' %>
			</a>
	  	<% end %>
	  	</div>
	  	</div>
	  <% else %>
	   	<div class="small-12 medium-3 large-3 columns">
	   	<div data-equalizer-watch="foo" class="panel" >
	   	<h4>
			<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'><%= post[1] %></a>
		</h4>
	   	<% if post[2] %>
	   	<script type="text/javascript">
	  	//alert('<%= ImageItem.find(post[2][0]).url_from_content.to_s %>');
	  	</script>
	   	<% if ImageItem.find(post[2][0]).url_from_content.include?('ttp:') %>
	  			<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
	  				<img src="h<%= ImageItem.find(post[2][0]).url_from_content %>"  alt="">
	  			</a>
	  			
	  		<% else %>
	  		<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
				<img src="../<%= ImageItem.find(post[2][0]).url_from_content %>"  alt="">
				</a>
	  		<% end %>
	   	<% else %>
	   	<a href='javascript:window.location.assign("<%= idea_store_show_post_url+'?post_id='+post[0].to_s%>")'>
	   		<%= image_tag 'default.jpg', alt: '图片' %>
	   		</a>
	   	<% end %>
	   	</div>
	   	
	   	</div>
	  <% end %>
	<% end %>
</div>
<script type="text/javascript">
	$(".panel").each(function(index, el) {
		if(index%3 == 0){
			$(this).addClass('callout')
		}	
	});
</script>
</section>
<div class="row pageDisplay">
<br>
	<div class="small-2 medium-3 large-3 columns columnsDisplay"></div>
	<div class="small-6 medium-6 large-6 columns columnsDisplay">
		<ul class="pagination">
		  <li class="arrow unavailable"><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i %>&first=1">&laquo;</a></li>
		  <% if @page.to_i < 2 and @page.to_i > 1 %>
		  <li><a href="<%= idea_store_index_url  %>?page=<%=@page-1 %>"><%= @page -1 %></a></li>
		  <% end %>
		  <% if @page.to_i < 4 and @page.to_i > 1 %>
		  <li><a href="<%= idea_store_index_url  %>?page=<%=@page-2 %>"><%= @page - 2 %></a></li>
		  <li><a href="<%= idea_store_index_url  %>?page=<%=@page-1 %>"><%= @page -1 %></a></li>
		  <% end %>
		  <li class="current"><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i %>"><%= @page.to_i %></a></li>
		  <li><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i+1%>"><%= @page.to_i+1 %></a></li>
		  <li><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i+2 %>"><%= @page.to_i+2 %></a></li>
		  <li class="unavailable"><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i+5 %>">&hellip;</a></li>
		  <li><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i+9 %>"><%= @page.to_i+9 %></a></li>
		  <li class="arrow"><a href="<%= idea_store_index_url  %>?page=<%=@page.to_i %>&last=1">&raquo;</a></li>
		</ul>
	</div>
	<div class="small-4 medium-3 large-3 columns columnsDisplay">
  
	</div>
	<br>
	
</div>
<div style="text-align:center">
		© 2015 <a href="<%= root_url %>" target="_blank">Laiber, Inc
	</div>

app/views/idea_store/post_a_post.html.erb
<style>
	.tag_to_submit{
		
		margin-right: 1rem;
	}
</style>
<div class="progress success round">
  <span class="meter" style="width: 0%;text-align:center"><span id="progress_text">加载完成！</span></span>
</div>
<%= form_for @post  do |f| %>
<div class="row display">
	<div class="small-3 medium-3 large-3 column">
		<div class="panel callout", id="tag_container">
		</div>
	<div class="panel" style="height:300px !important;">
 		<label>请选择分类</label>
		<% Tag.all.each_with_index do |tag,index| %>
      	<div style="float:left;width:auto;height:auto !important; background-color;"><input type="checkbox" id="tag_choose<%=index%>" class='tag-check' tag-id='<%=tag.id%>' ><span style="bottom:8px;position:relative;">&nbsp;&nbsp;<%= tag.name %>&nbsp;&nbsp;</span></div>
		<% end %>
		<%= hidden_field_tag :tag_ids, '' %>
		<%= hidden_field_tag :is_publish, '' %>
		<%= hidden_field_tag :from_foundation, 'true' %>
	</div>
	<div class="panel">
		<button type="submit" id="to_post_btn" is-publish="true">发表这个帖子</button>
		<button type="submit" id="to_save_btn" is-publish="false">存个草稿</button>
	</div>
	</div>
	<div class="small-9 medium-9 large-9 column">
		<div class="panel">
	 
      <%= hidden_field_tag :from_index,  "1" %>
      <% if session[:progress] %>
      <%= f.hidden_field :user_id, value: UserSession.find(session[:progress].fetch("_id").fetch("$oid")).user.id %>
      <% else %>
      	<% redirect_to user_active_login_path %>
      <% end %>
                <fieldset>
                  <%= f.label "帖子标题", for: 'doc-ta-1' %>
                   <div>
                     <%= f.text_field :title,:value=> @post_draft ? @post_draft.title : '', placeholder: '' %>
                  </div>
                </fieldset>
                <fieldset>
                      <div class="am-form-group">
                          <div><label for="doc-ta-1">正文</label></div>
                    <%= f.cktext_area :content, :value => @post_draft ? @post_draft.content.html_safe() : '', :ckeditor => {:uiColor => '#BDC0BA', :toolbar => 'full',:height => '60rem'} %>
                  </div>
                </fieldset>
      


</div>
	</div>
</div>

<div id="myModal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  
  <p id="errorM" class="lead">标题不得为空</p>
  
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<% end#end for form %>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<script type="text/javascript">
	$(document).ready(function(){
		//$('.top-bar-section').find('.left').hide();
		$('#progress_text').hide();
		$('.meter').animate(
			{width:'100%'},"slow",function(){
				$('#progress_text').show();
				$(this).parent().fadeOut(1500);
			});
		$('.tag-check').each(function(index){
			var is_changed = false;
			$(this).bind('change', function(event) {
				if(is_changed){
					is_changed = false;
					$(this).removeAttr('checked')
					$('#tag'+index).remove();

				}else{
					var tag =  '<span tag-index="'+index+'" class="tag_to_submit label round button" id="tag'+index+'">'
					tag = tag + $(this).parent().find('span').html();
					tag += '<span class="close">&times;</span></span>';
					$('.callout:first').append(tag);
					$(this).attr("checked","checked")
					is_changed = true;

					$('.tag_to_submit').each(function(index, el) {
					$(this).click(function(event) {
					var i = $(this).attr("tag-index");
					$('#tag_choose'+i).removeAttr('checked');
					$(this).remove();
			});
		});
				}
				
			});
		});
		

        $("#to_post_btn").click(function(event) {
        	$("#is_publish").val($(this).attr("is-publish"));
        });
        $("#to_save_btn").click(function(event) {
        	$("#is_publish").val($(this).attr("is-publish"));
        });
        var content = '';

        $("#new_post").submit(function(){
        	if($("#post_title").val()==''){
        		$('#myModal').foundation('reveal', 'open');
        		return false;
        	}
        	if ($.trim($("#tag_container").html()).length== 0) {
        		$("#errorM").html("请至少选择一个分类！");
        		$('#myModal').foundation('reveal', 'open');
        		return false;
        	}
        	$('input[checked]').each(function(index, el) {
        		content += '|^'+$(this).attr('tag-id');
        	});
        	$("#tag_ids").val(content);

        });
        
         	$('.tag-check').each(function(index, el) {
         		<% if @post_draft %>
        	 <% @post_draft.tags.each do |tag| %>
        		if($(this).attr('tag-id') == '<%= tag.id %>'){
        			$(this).trigger('change');
        			$('#progress_text').html("草稿保存成功！");
        		}

			<% end %>
        	<% end %>
        	});
         

	});
</script>

app/views/idea_store/show_post.html.erb
<style>
	.head-round{
		border-radius: 100px 100px 0px 100px; 
		-webkit-border-radius: 100px 100px 0px 100px; 
		-moz-border-radius: 100px 100px 0px 100px; 
		float:left;
		padding: 2rem;
		background-color: grey;
    	background-position: center; 

	}
	.collection{
		display: inline-block;
		margin-right: 4rem;
		float: right;
		position: relative;
		bottom: 2rem;
		cursor: pointer;

	}
	

</style>
<%= javascript_include_tag "user_active.js", 'data-turbolinks-track' => true %>
<div>
	<div>
		<div style="text-align: center;position:relative;top:-20px; height:5rem;font-size:3rem !important;font-weight:bolder;"><%= @post.title %><span style="float:right;font-size:1rem !important;top:3rem;right:2rem; !important;position:relative;">作者：<%= @post.user.name %><br>
		<script type="text/javascript">
			var last =new Date('<%=@post.created_at %>').toLocaleTimeString()
			document.write('<%=@post.created_at.to_s[0..9] %>'+last);
		</script>
		</span></div>
	</div>
	<div class="panel">
		<div style="width:auto;background-color:white;padding:40px !important;"><%= @post.content.html_safe() %></div>
		<div>
		<div style="clear:both;"><br>&nbsp;&nbsp;&nbsp;&nbsp;标签：
			<% @post.tags.each do |tag| %>
				<span tag-index="3" class="tag_to_submit label round button" id="tag3">&nbsp;&nbsp;<%= tag.name %>&nbsp;&nbsp;</span>
			<% end %>
		</div>
		<% if session[:progress] %>
		<% post_favor = PostFavor.where(user_id: @user_session.user.id, favor_post_id: @post.id).first %>
		<% if post_favor %>
		<div class="collection button small" postFavor='<%=post_favor.id %>' flag='cancel' id="post_collect">取消收藏</div>
		<% else %>
		<div class="collection button small" flag='collect' id="post_collect">❤收藏</div>
		<% end %>
		<% end %>
			<br>
		</div>
		<div>
		<% if @user_session %>
		<div style="text-align: center !important;position:relative !important; left:4rem !important;">
			<div class="head-round panel" style="display:inline-block;">
				<script type="text/javascript">
					$(document).ready(function(){
						$(".head-round").css("background-image",'url("<%= @user_session.user.head_url.headMini %>")');
						$(".head-round").css("background-repeat",'no-repeat');
					})
				</script>
			</div>
			
			<%= cktext_area_tag :content, @user_session.user.name+':说些什么呗！', :ckeditor => {:uiColor => '#BDC0BA', :toolbar => 'mini',:width => '80%',:height => '5rem'} %>
			</div>
		</div>
		<div class="panel display">
			<div class="button" id="commentBtn">提交</div>	
		</div>
		<% else  %>
		<div class="panel display">
			<div><a  class="button" href="<%= user_active_login_path %>">登录后可以评论</a></div>	
		</div>
		<% end  %>
		<div id="comment_panel" class="panel">
		<% Post.GetPostsFromParentPost(@post.id, 15).each do |comment|%>
		<div style="background-color:white;padding-right:4rem;marge-right:4rem;padding-left:4rem;marge-left:4rem !important;">
		<div id="head<%=comment.id%>" class="head-round panel" style="display:inline-block;">
				<script type="text/javascript">
					$(document).ready(function(){
						$("#head"+'<%= comment.id%>').css("background-image",'url("<%= comment.user.head_url.headMini %>")');
						$("#head"+'<%= comment.id%>').css("background-repeat",'no-repeat');
					})
				</script>
			</div>
			<div style="width:10%;font-weight:bolder;display:inline-block;float:left;"><%= comment.user.name %>:&nbsp;
			</div>
			<div style="width:auto;display:inline-block;clear:left;">
			<%  if comment.content %>
				<%= comment.content.html_safe() %>
				<% else %>
				他没有评论成功～
				<% end %>
			</div>
			<div style="font-size:small;bottom:1rem;">
				<script type="text/javascript">
					var last =new Date('<%=comment.created_at %>').toLocaleTimeString()
					document.write('<%=comment.created_at.to_s[0..9] %>'+last+"<br>");
				</script>
				<hr>
			</div>
		</div>
		<% end %>
		</div>
	</div>
	<div></div>
	<div></div>
</div>
<div id="myModal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  
  <p id="errorM" class="lead">标题不得为空</p>
  
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$("#post_collect").click(function(event) {
			if($(this).attr('flag') == 'collect'){
				$(this).html('取消收藏');
				$(this).attr('flag','cancel');
				var $obj = $("#myModal");
				var url = '<%= user_active_collect_post_path %>'
				var params = {post_id: '<%= @post.id %>',user_id: '<%= @post.user.id %>'}
				var flag = 'collect_post' ;
				ByPostText(params, $obj, url, flag);
				return false;
				
			}
			if($(this).attr('flag') == 'cancel'){
				$(this).html('收藏');
				$(this).attr('flag','collect');
				var $obj = $("#myModal");
				var url = '<%= user_active_cancel_collect_post_path %>'
				var params = {post_favor_id: $(this).attr('postFavor'),post_id: '<%= @post.id %>',user_id: '<%= @post.user.id %>'}
				var flag = 'collect_cancel' ;
				ByGetText(params, $obj, url, flag);
				return false;
			}
			
		});
		$('#commentBtn').click(function(event) {
                
                var father_post_id = '<%= @post.id %>';
                <% if session[:progress] %>
                  //================================ajax发评论
                  $.ajax({
                method: "GET",
                url: "<%= welcome_post_one_comment_path %>",
                beforeSend: function( xhr ) {
                  xhr.overrideMimeType( "text/plain; charset=utf-8" );
                  $(this).html('发送中...');
                 },
                data: {title: null, content: CKEDITOR.instances.content.getData(), user_id: '<%= @user_session.user_id %>', post_id: father_post_id},
                dataType: "json"
              }).done(function( msg ){ 
                $("#errorM").html('评论成功');
                window.location.reload();
        		$('#myModal').foundation('reveal', 'open');
              }).fail(function(){alert('请等待服务器');});
                  //===============================
                	$(this).html('提交');
                <% else %>
                  $("#errorM").html('请先<a href="<%= user_active_login_path %>">登录</a>');
        		$('#myModal').foundation('reveal', 'open');
                  return false;
                <% end %>
                
              });
	})
</script>