config/routes.rb
Rails.application.routes.draw do

  get 'investors/submit_info'
  
  get 'investors/index'

  get 'investors/reg'

  post 'investors/create'

  get 'investors/ban'

  get 'investors/pass'

  resources :post_favors
  get 'users/show_all_posts_by_user_id'
  get 'welcome/get_image_by_id'
  get 'welcome/get_next_15_posts'
  get 'user_active/is_collected'
  get 'user_active/to_follow'
  get 'user_active/cancel_collect_post'
  get 'idea_store/show_post'
  post 'user_active/collect_post'
  get 'user_active/login'
  get 'user_active/reg'
  get 'user_active/logout'
  get 'idea_store/post_a_post'
  get 'idea_store/get_posts'
  get 'idea_store/get_tags'
  get 'idea_store/get_session'
  get 'idea_store/get_one_post'
  get 'idea_store/get_comments'
  get 'idea_store/index'
  get 'idea_store/get_posts_from_topid'

  get 'invitation_admin/get_200_codes'
  get 'invitation_admin/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'
  get 'welcome/show_posts'
  get 'welcome/get_comments'
  get 'welcome/post_one_comment'
  get 'welcome/get_one_post'
  get 'welcome/get_tags'
  get 'get_test/index'
  post 'welcome/get_user_info'

  get 'personal_center/edit'

  post 'personal_center/upload'
  get 'personal_center/upload'
  patch 'personal_center/upload'

  devise_for :admins
  get 'personal_center/index'

  get 'user_mobile/is_name_exist'

  post 'user_mobile/create'
  post 'mobile_new_session/create'
  get 'mobile_new_session/create'

  get 'posts/all'

  post 'posts/all'

  get 'user_mobile/invite_judge'

  resources :posts

  get 'mobile_new_session/destory'

  get 'users/create_remote'

  get 'welcome/index'

  get 'user_sessions/user_exist'

  get 'user_sessions/success_info'

  post 'user_sessions/auth'

  resources :user_sessions

  resources :users

  root 'home#index'

  get 'mobile_app/posts/all'
  get 'mobile_app/posts/new'
  post 'mobile_app/posts/new'
  get 'mobile_app/posts/get'
  post 'mobile_app/posts/get'
  get 'mobile_app/posts/test'
  get 'mobile_app/posts/testName'

  get 'mobile_app/sign/signIn'
  post 'mobile_app/sign/signIn'
  get 'mobile_app/sign/autoSignIn'
  post 'mobile_app/sign/autoSignIn'
  get 'mobile_app/sign/signOut'
  post 'mobile_app/sign/signOut'

  get 'mobile_app/user/setPostFavor'
  post 'mobile_app/user/setPostFavor'
  get 'mobile_app/user/getFavorPosts'
  post 'mobile_app/user/getFavorPosts'
  get 'mobile_app/user/getRootPosts'
  post 'mobile_app/user/getRootPosts'

  get 'mobile_app/tags/all'
  post 'mobile_app/tags/all'

end

app/models/user_session.rb
class UserSession < ModelBase
	include Mongoid::Document
	include Mongoid::Timestamps
	belongs_to :user
	field :name, type: String
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:destroy, :user_exist]
  def new
  	@user = User.new
  end
  def index

  end

  def show

  end

  def user_exist
    #根据用户名，用户邮箱，用户手机号检测用户是否存在
     @user = User.where(:name => user_params[:user_attr]).first
      if @user.nil?
        @user = User.where(:email => user_params[:user_attr]).first
      end
      if @user.nil?
        @user = User.where(:mobile => user_params[:user_attr]).first
      end
      if @user
        render json: 1
      else
        render json: 0
      end
  end

  def auth

    	@user = User.where(:name => user_params[:name]).first
    	if @user.nil?
    		@user = User.where(:email => user_params[:name]).first
    	end
    	if @user.nil?
    		@user = User.where(:mobile => user_params[:name]).first
    	end
  		if @user
  			@user = @user.auth_pass(user_params[:password])
  			if @user
          @user_session = UserSession.new
          @user_session.user = @user
          @user_session.name = @user.name
          @user_session.save
          session[:progress] = @user_session
	  			respond_to do |format|
            if params[:page] == 'foundation'
              format.html{ redirect_to idea_store_index_path, notice: "欢迎，"+@user_session.name }
            else
              format.html{ redirect_to root_path, notice: "欢迎，"+@user_session.name }
            end

	  			end
	  		else
	  			respond_to do |format|
            if params[:page] == 'foundation'
              format.html{ redirect_to user_active_login_path, notice: "密码错误" }
            else
              format.html{ redirect_to new_user_session_path, notice: "密码错误" }
            end
  					
  				end
	  		end
  		else
  			respond_to do |format|
          if params[:page] == 'foundation'
              format.html{ redirect_to user_active_login_path, notice: "用户名不存在" }
            else
              format.html{ redirect_to new_user_session_path, notice: "用户名不存在" }
            end
          
  			end
  		end

  end

  def destroy
    @user_session = UserSession.find(params[:id])
    @user_sessions = UserSession.where(user: UserSession.find(session[:progress].fetch("_id").fetch("$oid")).user.id)
    @user_sessions.each do |sess|
      sess.destroy
    end
    session[:progress] = nil
    if @user_session.destroy
      if params[:page] == 'foundation'
        redirect_to idea_store_index_path, notice: "您已经退出！"
      else
        redirect_to root_url, notice: "您已经退出！"
      end
    end
  end


  def success_info
  	render json: session[:progress]
  end
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :screct_pass, :invite_code, :password, :user_attr)
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/auth.html.erb
<h1>hi</h1>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/index.html.erb
index.html.erb

app/views/user_sessions/new.html.erb
<%
  if notice == '1'
    %>
<script type="text/javascript">
    alert('注册成功！请登录');
</script>

    <%

  end
%>

<div class="login_content">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= form_for @user, url: user_sessions_auth_url, :html => {:class=> 'am-form am-form-horizontal'} do |f| %>
  <div class="am-form-group">
    <label for="doc-ipt-3" class="col-sm-2 am-form-label">账号</label>
    <div class="col-sm-10">
      <%= f.text_field :name, id: "doc-ipt-3", placeholder: "用户名/邮箱/手机号码" %>
    </div>
  </div>

  <div class="am-form-group">
    <label for="doc-ipt-pwd-2" class="col-sm-2 am-form-label">密码</label>
    <div class="col-sm-10">
      <%= f.password_field :password, id: "doc-ipt-3", placeholder: "请输入密码" %>
    </div>
  </div>

  <div class="am-form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox">记住十万年
        </label>
      </div>
    </div>
  </div>

  <div class="am-form-group">
    <div class="col-sm-offset-2 col-sm-10">
     <button type="submit" class="am-btn am-btn-primary am-btn-block">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录</button>
    </div>
  </div>
  <div class="forget_pw"><a href="<%= new_user_path %>">没有账号</a><a class="fg_pw" href="">忘记密码</a></div>
<% end %>
</div>

<script>
    $(document).ready(function(){
    $("#doc-ipt-3").blur(function(){
        var reuse=/^[a-zA-Z0-9_]{6,12}$/g;
   if (!reuse.test($("#doc-ipt-3").val())){
              if($("#doc-ipt-3").val()==="")
        {
         $(".Balert1").html('<i class="am-icon-frown-o"></i>&nbsp;密码不能为空')
        }
            else{
           $(".Balert1").html('<i class="am-icon-frown-o"></i>&nbsp;密码长度不对或者含有非法字符')
        }
        }
        else{
              $(".Balert1").html('<i class="am-icon-smile-o"></i>&nbsp;OK')
        };
    });
});



</script>

app/views/user_sessions/show.html.erb
show.html.erb